services:
  server:
    container_name: chatda-server
    build:
      context: .
    image: server
    ports:
      - 8081:80
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
